<div class="content-admin">

    <h1>Usuarios</h1>

    <br />

    <p>
        <a href="<?php echo $this->url('cms-admin-access/default',array('action'=>'new')); ?>" target="_self">Novo</a>
    </p>



    <table class="table">
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Email</th>
            <th>Ação</th>
        </tr>

        <?php foreach($this->data as $entity): ?>

        <?php $user = $entity->toArray(); ?>

        <tr>
        
            <td><?php echo $user['id']; ?></td>
            <td><?php echo $user['nome']; ?></td>
            <td><?php echo $user['email']; ?></td>
            <td>
                <a href="<?php echo $this->url('cms-admin-access/default',
                        array('controller'=>'users','action'=>'edit','id'=>$entity->getId()));?>" target="_self">Editar</a>
                
                <a href="<?php echo $this->url('cms-admin-access/default',
                        array('controller'=>'users','action'=>'delete','id'=>$entity->getId()));?>" target="_self">Delete</a>
                
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
    <br />

    <?php echo $this->paginationControl($this->data,'Sliding','partials/paginator'); ?>

</div>