<br><br>

<div ng-controller="CorretoresCtrl" class="row">

	<h2>Cadastro de Corretores</h2>	
	
	<form name="myForm" novalidate ng-submit="submit()">
		<div class="large-6 column">
			<INPUT TYPE="hidden" NAME="id" ng-model="corretor.id" />
			<label for="foto">
				Foto: 
				<input type="file" name="foto" ng-model="corretor.foto" accept="image/*" onchange="previewImage(this,[200],4);" data-app-filereader />
                <div class="imagePreview"></div>

                
			</label>

			<label for="nome">Nome: 
				<input type="text" name="nome" ng-model="corretor.nome" ng-minlength=5  placeholder="Escreva o seu nome" required>

				<div class="error" 
        ng-show="myForm.nome.$dirty && myForm.nome.$invalid">
					<small class="error" 
					ng-show="myForm.nome.$error.required">
						O nome é obrigatorio
					</small>
					<small class="error" 
					    ng-show="myForm.nome.$error.minlength">
					    O nome é obrigatorio e deve ter pelo menos 5 caracteres
					</small>
					<small class="error" 
					    ng-show="myForm.nome.$error.maxlength">
					    O nome não pode ter mais de 20 caracteres
					</small>
				</div>
			</label>

			<label for="area">
				<select ng-model="corretor.area" name="area" ng-options="area.nome for area in areas">
					<option value="">-- Escolha a Area --</option>
				</select>
				<span class="error" ng-show="myForm.area.$error.required">required</span>
			</label>

			<label for="cargo">
				<select ng-model="corretor.cargo" name="cargo" ng-options="cargo.nome for cargo in cargos">
					<option value="">-- Escolha o Cargo --</option>
				</select>
				<span class="error" ng-show="myForm.cargo.$error.required">required</span>
			</label>
			<label for="email">
				E-mail: 
				<input type="text" name="email" ensure-unique ng-model="corretor.email" ng-minlength=8 required placeholder="Escreva o seu email">
				<div class="error-container" 
	     ng-show="myForm.email.$dirty && myForm.email.$invalid">
					<small class="error" 
					ng-show="myForm.email.$error.required">
						O email é obrigatorio
					</small>
					<small class="error" 
					ng-show="myForm.email.$error.minlength">
						O email é obrigatorio e deve ter pelo menos 8 caracteres
					</small>
					<small class="error" 
					ng-show="myForm.email.$error.email">
						O email não é válido
					</small>
					<small class="error" ng-show="myForm.email.$error.unique && showErroUnique" >
						Este email já foi cadastrado

					</small>
					<span ng-show="myForm.email.$error.unique && !showErroUnique">Verificando email...</span>
				</div>
			</label>
		</div>
		
		<div class="large-6 column">
			

			<fieldset>
				<legend>Telefones</legend>
				<label for="telefone">
					
					<input type="text" name="telefones" ng-model="corretor.telefones[0].num">
					<select ng-model="corretor.telefones[0].tipo" name="cargo" ng-options="tipo.nome for tipo in tipos">
						<option value="">-- Escolha o Tipo --</option>
					</select>
					<input type="text" name="telefones" ng-model="corretor.telefones[1].num">
					<select ng-model="corretor.telefones[1].tipo" name="cargo" ng-options="tipo.nome for tipo in tipos">
						<option value="">-- Escolha o Tipo --</option>
					</select>
					<input type="text" name="telefones" ng-model="corretor.telefones[2].num">
					<select ng-model="corretor.telefones[2].tipo" name="cargo" ng-options="tipo.nome for tipo in tipos">
						<option value="">-- Escolha o Tipo --</option>
					</select>
				</label>
			</fieldset>

			<button ng-click="submit(myForm.$valid)" ng-disabled="myForm.$invalid">Enviar</button>

		</div>
	</form>
	<hr>
	<div class="large-12 columns">
		<h2>Corretores Cadastrados</h2>
		<div ng-show="loading">Carregando dados...</div>

		<table id="tabela-corretores" ng-hide="loading" width="100%">
			<thead>
				<tr>
					<th>ID</th>
					<th>Nome</th>
					<th>Area</th>
					<th>Cargo</th>
					<th>E-mail</th>
					<th>Foto</th>
					<th>Telefones</th>
					<th>Ação</th>
				</tr>
			</thead>
			<tbody>
				<tr ng-repeat="corretor in corretores">
					<td>{{ corretor.id }}</td>
					<td>{{ corretor.nome }}</td>
					<td>{{ corretor.area }}</td>
					<td>{{ corretor.cargo }}</td>
					<td>{{ corretor.email }}</td>
					<td>{{ corretor.foto }}</td>
					<td>
						{{ corretor.telefones }}
					</td>
					<td><a href="">Editar</a>|<a href="">Excluir</a></td>
				</tr>
			</tbody>
		</table>
	</div>

</div>