<br><br>

<style>
	#corretorCadastrado {
		display: none;
	}
</style>

<div ng-controller="CorretoresCtrl" class="row">

	<h2>Cadastro de Colaboradores</h2>	

	<div id="corretorCadastrado" data-alert class="alert-box success radius">
		O colaborador foi salvo com sucesso! ID: {{ cadastronovo.id }} | Nome: {{ cadastronovo.nome }}
		<a href="#" class="close">&times;</a>
	</div>
	
	<form name="myForm" novalidate>

		<div class="row">

			<div class="large-6 small-12 column">

				<div ng-show="setNova" width="100%; text-align: center">
	           		<img id="fotoCorretor" src="{{ enderecoFoto }}" alt="Foto do Corretor">
	           	</div>

	           	

	           	<br>
				<INPUT TYPE="hidden" NAME="id" ng-model="corretor.id" />

				

				<div class="row collapse">	

					<div class="small-3 columns">
			          	<label for="foto">
							Foto: 
						</label>
			        </div>

			        <div class="small-9 columns">
			          	<input type="file" name="foto" ng-model="corretor.foto" accept="image/*" onchange="previewImage(this,[200],4);" data-app-filereader />

			          	<div class="imagePreview" ng-hide="setNova"></div>
			        </div>

		            

            	</div>

            	<div class="row collapse">	

					<div class="small-3 columns">
			          	<label for="nome">
							Nome:
						</label>
			        </div>

			        <div class="small-9 columns">
			          	<input type="text" name="nome" ng-model="corretor.nome" ng-minlength=5  placeholder="Escreva o seu nome" required>

						<div class="error" 
			    ng-show="myForm.nome.$dirty && myForm.nome.$invalid">
							<small class="error" 
							ng-show="myForm.nome.$error.required">
								O nome é obrigatorio
							</small>
							<small class="error" 
							    ng-show="myForm.nome.$error.minlength">
							    O nome é obrigatorio e deve ter pelo menos 5 caracteres
							</small>
							<small class="error" 
							    ng-show="myForm.nome.$error.maxlength">
							    O nome não pode ter mais de 20 caracteres
							</small>
						</div>
			        </div>

            	</div>

				<div class="row collapse">	

					<div class="small-3 columns">
						<label for="email">
							E-mail: 
						</label>
			        </div>

			        <div class="small-9 columns">
			          	<input type="text" name="email" ensure-unique ng-model="corretor.email" ng-minlength=8 required placeholder="Escreva o seu email">
						<div class="error-container" 
			     ng-show="myForm.email.$dirty && myForm.email.$invalid">
							<small class="error" 
							ng-show="myForm.email.$error.required">
								O email é obrigatorio
							</small>
							<small class="error" 
							ng-show="myForm.email.$error.minlength">
								O email é obrigatorio e deve ter pelo menos 8 caracteres
							</small>
							<small class="error" 
							ng-show="myForm.email.$error.email">
								O email não é válido
							</small>
							<small class="error" ng-show="myForm.email.$error.unique && showErroUnique" >
								Este email já foi cadastrado

							</small>
							<span ng-show="myForm.email.$error.unique && !showErroUnique">Verificando email...</span>
						</div>
			        </div>
		            
            	</div>
				
			</div>
			
			<div class="large-6 small-12 column">

				<div class="row collapse">	

					<div class="small-3 columns">
			          	<label for="area">
							Area: 
						</label>
			        </div>

			        <div class="small-9 columns">
			          	<select ng-model="corretor.area" name="area" ng-options="area.nome for area in areas">
							<option value="">-- Escolha a Area --</option>
						</select>
						<span class="error" ng-show="myForm.area.$error.required">Você deve selecionar uma área</span>
			        </div>
		            
            	</div>
				
				<div class="row collapse">	

					<div class="small-3 columns">
			          	<label for="cargo">
							Cargo: 
						</label>
			        </div>

			        <div class="small-9 columns">
			          	<select ng-model="corretor.cargo" name="cargo" ng-options="cargo.nome for cargo in cargos">
							<option value="">-- Escolha o Cargo --</option>
						</select>
						<span class="error" ng-show="myForm.cargo.$error.required">Você deve selecionar um cargo</span>
			        </div>
		            
            	</div>

				<div class="row collapse">	

					<div class="small-3 columns">
						<label>
							Telefone 1: 
						</label>
			        </div>

			        <div class="small-6 columns">
			          	<input type="text" name="telefones" ng-model="corretor.telefones[0].num">
			        </div>
			        <div class="small-3 columns">
			        	<select ng-model="corretor.telefones[0].tipo" name="tipo" style="font-family: 'icomoon', sans-serif;">
							<option value="celular">&#xe602; Celular</option>
							<option value="telefone">&#xe601; Telefone</option>
							<option value="fax">&#xe603; Fax</option>
						</select>
			        </div>
				</div>

				<div class="row collapse">	
			        <div class="small-3 columns">
						<label>
							Telefone 2: 
						</label>
			        </div>

			        <div class="small-6 columns">
			          	<input type="text" name="telefones" ng-model="corretor.telefones[1].num">
			        </div>
			        <div class="small-3 columns">
			        	<select ng-model="corretor.telefones[1].tipo" name="tipo" style="font-family: 'icomoon', sans-serif;">
							<option value="celular">&#xe602; Celular</option>
							<option value="telefone">&#xe601; Telefone</option>
							<option value="fax">&#xe603; Fax</option>
						</select>
			        </div>
				</div>

				<div class="row collapse">	
			        <div class="small-3 columns">
						<label>
							Telefone 3: 
						</label>
			        </div>

			        <div class="small-6 columns">
			          	<input type="text" name="telefones" ng-model="corretor.telefones[2].num">
			        </div>
			        <div class="small-3 columns">
			        	<select ng-model="corretor.telefones[2].tipo" name="tipo" style="font-family: 'icomoon', sans-serif;">
							<option value="celular">&#xe602; Celular</option>
							<option value="telefone">&#xe601; Telefone</option>
							<option value="fax">&#xe603; Fax</option>
						</select>
			        </div>
		       	</div>

					
				<button ng-hide="corretor.id" class="btn-enviar-form button expand" ng-click="createForm(myForm.$valid)" ng-disabled="myForm.$invalid">Cadastrar</button>

				<button ng-show="corretor.id" class="btn-enviar-form button success expand" ng-click="saveForm(myForm.$valid)" ng-disabled="myForm.$invalid">Salvar</button>

			</div>
		</div>
	</form>

	<hr>
	
	<div class="row">
		<div class="large-12 columns">
			<h2>Colaboradores Cadastrados</h2>
			<div ng-show="loading">Carregando dados...</div>

			<table id="tabela-corretores" ng-hide="loading" width="100%">
				<thead>
					<tr>
						<th>ID</th>
						<th>Nome</th>
						<th>Area</th>
						<th>Cargo</th>
						<th>E-mail</th>
						<th>Foto</th>
						<th>Telefones</th>
						<th>Ação</th>
					</tr>
				</thead>
				<tbody>
					<tr ng-repeat="corretor in corretores">
						<td>{{ corretor.id }}</td>
						<td>{{ corretor.nome }}</td>
						<td>{{ corretor.area }}</td>
						<td>{{ corretor.cargo }}</td>
						<td>{{ corretor.email }}</td>
						<td>{{ corretor.foto }}</td>
						<td>
							{{ corretor.telefones }}
						</td>
						<td><a href="/admin/content/corretores/edit/{{ corretor.id }}">Editar</a>|<a href="/admin/content/corretores/delete/{{ corretor.id }}">Excluir</a></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>

</div>