<h3>Nova Página</h3>
<br />
<?php

$form = $this->form;
$form->setAttribute('action', $this->url('cms-admin-content/default',array('controller'=>'posts','action'=>'new')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>

<?php echo $this->inlineScript()
				->prependFile($this->basePath() . '/js/ckeditor.js')

; ?>

<script>
	CKEDITOR.replace( 'textarea-content' )
</script>