<h3>Novo Arquivo</h3>
<br />
<?php

$form = $this->form;
$form->setAttribute('action', $this->url('cms-admin-content/default',array('controller'=>'arquivostexto','action'=>'new')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>

<?php echo $this->inlineScript()
				->prependFile($this->basePath() . '/js/ckeditor.js')

; ?>